package ydbtemplate

import (
	"context"
	"errors"
	"io"

	db "github.com/compoundinvest/stockfundamentals/internal/infrastructure/db/shared"
	ydbfilter "github.com/compoundinvest/stockfundamentals/internal/infrastructure/db/shared/ydb-filter"
	"github.com/compoundinvest/stockfundamentals/internal/interface/shared"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
	"github.com/ydb-platform/ydb-go-sdk/v3/sugar"
)

/*
This universal template method can be used for fetching a particular entity from the database by simply providing the type and the table name.
The corresponding YQL queries are auto-generated by scanning the "sql" tag in each field. The method might be used to avoid reusing the same boilerplate
code for the simple filtered data retrieval of a particular entity.

If pagination is not required, simply provide the zero values for the query parameter (shared.ParsedApiQuery{})
*/
func GetFilteredEntity[T any](filters []ydbfilter.YdbFilter, query shared.ParsedApiQuery, tablePath string) ([]T, error) {
	if query.PageSize == 0 { //No pagination required
		return GetEntity[T](query.Filters, tablePath)
	} else {
		return GetPaginatedEntity[T](tablePath, query.SortByColumn, query.SortDirection, query.PageSize, query.Filters)
	}
}

// Deprecated: Use GetFilteredEntity instead
func GetEntity[T any](filters []ydbfilter.YdbFilter, tablePath string) ([]T, error) {
	dbValues := []T{}
	dbConnection, err := db.GetReusableYdbDriver()
	if err != nil {
		return dbValues, err
	}
	defer db.ReleaseDriver(dbConnection)

	yql, err := generateGetQuery[T](filters, "", "", tablePath, 0)
	if err != nil {
		return dbValues, err
	}

	dbValues, err = GetEntityWithCustomQuery[T](filters, yql)
	if err != nil {
		return dbValues, err
	}

	return dbValues, nil
}

func GetPaginatedEntity[T any](tablePath, sortBy, sortDirection string, pageSize int, filters []ydbfilter.YdbFilter) ([]T, error) {
	dbValues := []T{}
	dbConnection, err := db.GetReusableYdbDriver()
	if err != nil {
		return dbValues, err
	}
	defer db.ReleaseDriver(dbConnection)

	yql, err := generateGetQuery[T](filters, sortBy, sortDirection, tablePath, pageSize)
	if err != nil {
		return dbValues, err
	}

	dbValues, err = GetEntityWithCustomQuery[T](filters, yql)
	if err != nil {
		return dbValues, err
	}

	return dbValues, nil
}

func GetEntityWithCustomQuery[T any](filters []ydbfilter.YdbFilter, yqlQuery string) ([]T, error) {
	dbValues := []T{}
	dbConnection, err := db.GetReusableYdbDriver()
	if err != nil {
		return dbValues, err
	}
	defer db.ReleaseDriver(dbConnection)

	//Query parameters that will be set in the query during execution
	params := ydbfilter.SetQueryParams(filters)

	err = dbConnection.Query().Do(context.TODO(),
		func(ctx context.Context, s query.Session) (err error) {
			result, err := s.Query(
				ctx,
				yqlQuery,
				query.WithTxControl(query.TxControl(query.BeginTx(query.WithSnapshotReadOnly()))),
				query.WithParameters(params))

			if err != nil {
				return err
			}

			defer func() {
				_ = result.Close(ctx)
			}()

			for {
				resultSet, err := result.NextResultSet(ctx)
				if err != nil {
					if errors.Is(err, io.EOF) {
						break
					}

					return err
				}

				for row, err := range sugar.UnmarshalRows[T](resultSet.Rows(ctx)) {
					if err != nil {
						return err
					}

					dbValues = append(dbValues, row)
				}
			}

			return nil
		},
	)
	if err != nil {
		return dbValues, err
	}

	return dbValues, nil
}
