package ydbtemplate

import (
	"context"
	"errors"
	"io"

	db "github.com/compoundinvest/stockfundamentals/internal/infrastructure/db/shared"
	ydbfilter "github.com/compoundinvest/stockfundamentals/internal/infrastructure/db/shared/ydb-filter"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
	"github.com/ydb-platform/ydb-go-sdk/v3/sugar"
)

/*
This universal template method can be used for fetching a particular entity from the database by simply providing the type and the table name.
The corresponding YQL queries are auto-generated by scanning the "sql" tag in each field. The method might be used to avoid reusing the same boilerplate
code for the simple filtered data retrieval of a particular entity
*/

func GetEntity[T any](filters []ydbfilter.YdbFilter, tablePath string) ([]T, error) {
	dbValues := []T{}
	dbConnection, err := db.GetReusableYdbDriver()
	if err != nil {
		return dbValues, err
	}
	defer db.ReleaseDriver(dbConnection)

	yql, err := generateGetQuery[T](filters, tablePath)
	if err != nil {
		return dbValues, err
	}

	err = dbConnection.Query().Do(context.TODO(),
		func(ctx context.Context, s query.Session) (err error) {
			result, err := s.Query(
				ctx,
				yql,
				query.WithTxControl(query.TxControl(query.BeginTx(query.WithSnapshotReadOnly()))),
				query.WithParameters(ydbfilter.SetQueryParams(filters)))

			if err != nil {
				return err
			}

			defer func() {
				_ = result.Close(ctx)
			}()

			for {
				resultSet, err := result.NextResultSet(ctx)
				if err != nil {
					if errors.Is(err, io.EOF) {
						break
					}

					return err
				}

				for row, err := range sugar.UnmarshalRows[T](resultSet.Rows(ctx)) {
					if err != nil {
						return err
					}

					dbValues = append(dbValues, row)
				}
			}

			return nil
		},
	)
	if err != nil {
		return dbValues, err
	}

	return dbValues, nil
}
