package stockoverview

import pb "opensource.tbank.ru/invest/invest-go/proto"

func mapTinkoffOverviewToInternal(tOverview *pb.GetAssetFundamentalsResponse_StatisticResponse) StockOverview {
	overview := StockOverview {
		Figi: tOverview.AssetUid,
		Currency: tOverview.Currency,
		MarketCapitalization: tOverview.MarketCapitalization,
		HighPriceLast_52Weeks: tOverview.HighPriceLast_52Weeks,
		LowPriceLast_52Weeks: tOverview.LowPriceLast_52Weeks,
		AverageDailyVolumeLast_10Days: tOverview.AverageDailyVolumeLast_10Days,
		AverageDailyVolumeLast_4Weeks: tOverview.AverageDailyVolumeLast_4Weeks,
		Beta: tOverview.Beta,
		FreeFloat: tOverview.FreeFloat,
		ForwardAnnualDividendYield: tOverview.ForwardAnnualDividendYield,
		SharesOutstanding: tOverview.SharesOutstanding,
		RevenueTtm: tOverview.RevenueTtm,
		EbitdaTtm: tOverview.EbitdaTtm,
		NetIncomeTtm: tOverview.NetIncomeTtm,
		EpsTtm: tOverview.EpsTtm,
		DilutedEpsTtm: tOverview.DilutedEpsTtm,
		FreeCashFlowTtm: tOverview.FreeCashFlowTtm,
		FiveYearAnnualRevenueGrowthRate: tOverview.FiveYearAnnualRevenueGrowthRate,
		PriceToSalesTtm: tOverview.PriceToSalesTtm,
		PriceToBookTtm: tOverview.PriceToBookTtm,
		PriceToFreeCashFlowTtm: tOverview.PriceToFreeCashFlowTtm,
		TotalEnterpriseValueMrq: tOverview.TotalEnterpriseValueMrq,
		EvToEbitdaMrq: tOverview.EvToEbitdaMrq,
		NetMarginMrq: tOverview.NetMarginMrq,
		NetInterestMarginMrq: tOverview.NetInterestMarginMrq,
		Roe: tOverview.Roe,
		Roa: tOverview.Roa,
		Roic: tOverview.Roic,
		TotalDebtMrq: tOverview.TotalDebtMrq,
		TotalDebtToEquityMrq: tOverview.TotalDebtToEquityMrq,
		TotalDebtToEbitdaMrq: tOverview.TotalDebtToEbitdaMrq,
		FreeCashFlowToPrice: tOverview.FreeCashFlowToPrice,
		NetDebtToEbitda: tOverview.NetDebtToEbitda,
		CurrentRatioMrq: tOverview.CurrentRatioMrq,
		FixedChargeCoverageRatioFy: tOverview.FixedChargeCoverageRatioFy,
		DividendsPerShare: tOverview.DividendsPerShare,
		FiveYearsAverageDividendYield: tOverview.FiveYearsAverageDividendYield,
		FiveYearAnnualDividendGrowthRate: tOverview.FiveYearAnnualDividendGrowthRate,
		DividendPayoutRatioFy: tOverview.DividendPayoutRatioFy,
		BuyBackTtm: tOverview.BuyBackTtm,
		OneYearAnnualRevenueGrowthRate: tOverview.OneYearAnnualRevenueGrowthRate,
		DomicileIndicatorCode: tOverview.DomicileIndicatorCode,
		AdrToCommonShareRatio: tOverview.AdrToCommonShareRatio,
		NumberOfEmployees: tOverview.NumberOfEmployees,
		ExDividendDate: tOverview.ExDividendDate.AsTime(),
		FiscalPeriodStartDate: tOverview.FiscalPeriodStartDate.AsTime(),
		FiscalPeriodEndDate: tOverview.FiscalPeriodEndDate.AsTime(),
		RevenueChangeFiveYears: tOverview.RevenueChangeFiveYears,
		EpsChangeFiveYears: tOverview.EpsChangeFiveYears,
		EbitdaChangeFiveYears: tOverview.EbitdaChangeFiveYears,
		TotalDebtChangeFiveYears: tOverview.TotalDebtChangeFiveYears,
		EvToSales: tOverview.EvToSales,
	}

	return overview
}
